### ISSUE TITLE
Sepertinya Belum Dipush Semua

### ISSUE THREAD

**Issue by endytc** [andriawan/AndKasir#3]
untuk class ini blm dipush gan andriawan.safe.password.SafePassword;
hehe... :)

**Comment by andriawan** [comment]
Terima kasih telah membuka issue demi pengembangan aplikasi. modul tersebut memang modul custom yang saya buat sendiri...didalamnya ada lib eksternal juga. Namun saya jadikan satu agar memudahkan. Silahkan ambil di release terbaru https://github.com/andriawan/AndKasir/releases/download/v0.5/AndKasir-v0.5.tar.gz
