### ISSUE TITLE
Bug Function Login

### ISSUE THREAD

**Issue by fajaregafirmansyah** [andriawan/AndKasir#5]
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class andriawan.kasir.controller.UserLoginController.

Man ini kesalahan apa ya?

**Comment by fajaregafirmansyah** [comment]
Kasurnya pada saat Login

**Comment by andriawan** [comment]
terima kasih mas @fajaregafirmansyah telah membuat issue. issue berguna untuk membantu user lain menyelesaikan  masalah yang sama dan juga untuk kepentingan pengembangan aplikasi.

Untuk issue yang sedang mas @fajaregafirmansyah hadapi, saya butuh info detail tambahan (misal screenshot, konfigurasi, OS yang dipakai) untuk bisa toubleshooting issue tersebut. minimnya info dari issue, akan menyulitkan pengembang memecahkan issue yang ada,

**Comment by fajaregafirmansyah** [comment]
Terima kasih @andriawan atas bantuannya.

1. Gambar Pada Saat Hendak Login Menggunakan username kasir

![bukti1](https://user-images.githubusercontent.com/21186672/61107100-33620180-a4a9-11e9-8c27-9be38230153b.PNG)

2. Kesalahan Ditemukan.

![bukti2](https://user-images.githubusercontent.com/21186672/61107098-33620180-a4a9-11e9-9a21-c3531e767677.PNG)

3. Gambar Mengacu kesalahan pada saat panggil UserLoginController

![bukti3](https://user-images.githubusercontent.com/21186672/61107226-994e8900-a4a9-11e9-8743-29f4f0ae4d91.PNG)

Spesifikasi :
Asus
Java 8

Kira-kira  seperti itu mas @andriawan ...

**Comment by andriawan** [comment]
terima kasih atas respondnya mas @fajaregafirmansyah. beradasarkan informasi diatas, troubleshoot dari saya ialah
- Cek di IDE netbeans yang mas @fajaregafirmansyah gunakan. Apakah file yang menyimpan class UserLoginController tersedia.
- Pastikan tidak ada indikasi error dari IDE netbeans. Biasanya file akan dihighlight merah jika ada kesalahan pada sebuah file
- Pastikan mengikuti panduan di file README.md

**Comment by fajaregafirmansyah** [comment]
Terima kasih mas @andriawan .. tapi setelah di cek pada kelas UserLoginController ada mas.
Kira-kira solusi lainnya gimana ya mas?

**Comment by fajaregafirmansyah** [comment]
Oke mas @andriawan sudah solve issue ini. Alhamdulillah sudah berhasil. Makasih banyak ilmunya mas @andriawan sudah berbagi.. Semoga dibalas oleh Allah dengan kebaikan dan dijadikan ilmu yang bermanfaat.

**Comment by andriawan** [comment]
Alhamdulillah. Agar user lain mendapatkan manfaat dan informasi mengenai cara menangani issue yang mas @fajaregafirmansyah alami. Mohon sekiranya untuk memberikan informasi detail mengenai pemecahan masalah di thread comment issue. Agar kita juga bisa mendapatkan manfaat dan pelajaran yang sama. Terima kasih atas dukungan dan semangat memajukan aplikasi AndKasir ini. Semoga bermanfaat bagi semua. Kontribusi sangat diperlukan. Saya mengharapkan kontribusi sekecil apapun baik pelaporan bug atau pengajuan code agar aplikasi ini semakin baik dan dapat digunakan secara luas.

**Comment by fajaregafirmansyah** [comment]
Alhamdulillah siap mas @andriawan insyaAllah saya share bagaimana saya memecahkan masalah tersebut.

Ada kesalahan lagi mas ketika saya coba klik cek barang
![eaa](https://user-images.githubusercontent.com/21186672/61114117-dae73000-a4b9-11e9-9ce5-11166682c35a.PNG)

**Comment by andriawan** [comment]
Itu sepertinya issue di struktur database

**Comment by fajaregafirmansyah** [comment]
file kasir.sql yg udh fix ada mas?

**Comment by andriawan** [comment]
mas @fajaregafirmansyah clone di branch yang mana?
